name: beinex_ecom
description: "Beinex E-com Application"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  http: ^0.13.6
  json_annotation: ^4.9.0

  auto_route: ^10.2.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.1.1

  flutter_local_notifications: ^18.0.1
  fl_chart: ^0.66.1
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.6.1
  auto_route_generator: ^10.2.5

flutter:
  uses-material-design: true